spring:
  profiles:
    active: dev
  datasource:
      url: jdbc:mysql://${jdbc.hostName}:${jdbc.hostPort}/${jdbc.dbName}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
      username: ${jdbc.userName}
      password: ${jdbc.password}
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

mybatis:
  mapperLocations: classpath:mapper/*.xml

##jwt配置
audience:
  clientId: 098f6bcd4621d373cade4e832627b4f6
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  name: restapiuser
  expiresSecond: 3600

thymeleaf:
  enabled: true
  cache: false
  content-type: text/html
  suffix: .html
  prefix: classpath:/templates/
  cache-period: 0
  mode: LEGACYHTML5
  template:
    cache: false

spring.mvc.static-path-pattern: /**
spring.resources.static-locations: classpath:/META-INF/resources/,classpath:/static/,file:./upload/